title: Comparte tu código
hero_image: images/banner.png
description: Comparte tu proyecto de MakeCode
version: 4
listed: false
copyedit: false
last_tested: "2023-10-03"
steps:
  - 
    title: Introducción
