---
title: Rhannwch eich côd
hero_image: images/banner.png
description: Rhannwch eich prosiect MakeCode
version: 4
listed: false
copyedit: false
last_tested: "2023-10-03"
steps:
  - title: Cyflwyniad
