title: Κοινοποίησε τον κώδικά σου
hero_image: images/banner.png
description: Μοιράσου το έργο σου MakeCode
version: 4
listed: false
copyedit: false
last_tested: "2023-10-03"
steps:
  - 
    title: Εισαγωγή
